[docs]
    version = "0.9"
    basePath = "node_modules/@gethinode/hinode"

# Remove the toggle button for light or dark mode
[main]
    enableDarkMode = false

[navigation]
anchor = true
logo = "/img/kokkos-logo.png"
color = "body"
fixed = true
offset = "3.8em"
search = true
breadcrumb = false
toc = true
sidebar = true

[home]
    sections = ["blog"]
    featurePhoto = ""
    fullCover = true
    centerHeadLine = false
    style = ""

[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        separator = true

[style]
    primary = "#2596be"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    themeFont = "Inter"
    themeFontPath = "/fonts"

[links]
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    hinode_docs = "https://gethinode.com/docs"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    utterances = "https://utteranc.es"
 